services:
  httpd:
    working_dir: /workspace
    image: golang:1.21.3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env
    command: sh -c "go run public/main.go"
    volumes:
      - ${PWD}:/workspace
    ports:
      - "8080:8080"
      - "8081:8081"

  mysql:
    image: mysql:8
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    volumes:
      - ./.docker/mysql:/var/lib/mysql