// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/dns2012/dealls-dating-service/app/usecase"
	mock "github.com/stretchr/testify/mock"
)

// CreateUserPreferenceUsecase is an autogenerated mock type for the CreateUserPreferenceUsecase type
type CreateUserPreferenceUsecase struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, params
func (_m *CreateUserPreferenceUsecase) Call(ctx context.Context, params *usecase.CreateUserPreferenceUsecaseParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.CreateUserPreferenceUsecaseParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCreateUserPreferenceUsecase creates a new instance of CreateUserPreferenceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateUserPreferenceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateUserPreferenceUsecase {
	mock := &CreateUserPreferenceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
