// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/dns2012/dealls-dating-service/app/usecase"
	mock "github.com/stretchr/testify/mock"
)

// ListUserUsecase is an autogenerated mock type for the ListUserUsecase type
type ListUserUsecase struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, params
func (_m *ListUserUsecase) Call(ctx context.Context, params *usecase.ListUserUsecaseParams) (*usecase.ListUserUsecaseResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *usecase.ListUserUsecaseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.ListUserUsecaseParams) (*usecase.ListUserUsecaseResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.ListUserUsecaseParams) *usecase.ListUserUsecaseResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.ListUserUsecaseResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.ListUserUsecaseParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewListUserUsecase creates a new instance of ListUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListUserUsecase {
	mock := &ListUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
