// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/dns2012/dealls-dating-service/app/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MeUsecase is an autogenerated mock type for the MeUsecase type
type MeUsecase struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, params
func (_m *MeUsecase) Call(ctx context.Context, params *usecase.MeUsecaseParams) (*usecase.MeUsecaseResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *usecase.MeUsecaseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.MeUsecaseParams) (*usecase.MeUsecaseResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.MeUsecaseParams) *usecase.MeUsecaseResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.MeUsecaseResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.MeUsecaseParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMeUsecase creates a new instance of MeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeUsecase {
	mock := &MeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
