// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/dns2012/dealls-dating-service/app/usecase"
	mock "github.com/stretchr/testify/mock"
)

// OrderPackageUsecase is an autogenerated mock type for the OrderPackageUsecase type
type OrderPackageUsecase struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, params
func (_m *OrderPackageUsecase) Call(ctx context.Context, params *usecase.OrderPackageUsecaseParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OrderPackageUsecaseParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderPackageUsecase creates a new instance of OrderPackageUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPackageUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPackageUsecase {
	mock := &OrderPackageUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
