// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	v1 "github.com/dns2012/dealls-dating-service/proto/schema/v1"
)

// PackageSchemaServer is an autogenerated mock type for the PackageSchemaServer type
type PackageSchemaServer struct {
	mock.Mock
}

// ListPackage provides a mock function with given fields: _a0, _a1
func (_m *PackageSchemaServer) ListPackage(_a0 context.Context, _a1 *emptypb.Empty) (*v1.ListPackageResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListPackage")
	}

	var r0 *v1.ListPackageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty) (*v1.ListPackageResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty) *v1.ListPackageResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListPackageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderPackage provides a mock function with given fields: _a0, _a1
func (_m *PackageSchemaServer) OrderPackage(_a0 context.Context, _a1 *v1.OrderPackageRequest) (*emptypb.Empty, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for OrderPackage")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.OrderPackageRequest) (*emptypb.Empty, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.OrderPackageRequest) *emptypb.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.OrderPackageRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedPackageSchemaServer provides a mock function with given fields:
func (_m *PackageSchemaServer) mustEmbedUnimplementedPackageSchemaServer() {
	_m.Called()
}

// NewPackageSchemaServer creates a new instance of PackageSchemaServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPackageSchemaServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PackageSchemaServer {
	mock := &PackageSchemaServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
