// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/dns2012/dealls-dating-service/app/usecase"
	mock "github.com/stretchr/testify/mock"
)

// RegisterUsecase is an autogenerated mock type for the RegisterUsecase type
type RegisterUsecase struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, params
func (_m *RegisterUsecase) Call(ctx context.Context, params *usecase.RegisterUsecaseParams) (*usecase.RegisteUsecaseResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *usecase.RegisteUsecaseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.RegisterUsecaseParams) (*usecase.RegisteUsecaseResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.RegisterUsecaseParams) *usecase.RegisteUsecaseResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.RegisteUsecaseResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.RegisterUsecaseParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRegisterUsecase creates a new instance of RegisterUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterUsecase {
	mock := &RegisterUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
