// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAuthSchemaServer is an autogenerated mock type for the UnsafeAuthSchemaServer type
type UnsafeAuthSchemaServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAuthSchemaServer provides a mock function with given fields:
func (_m *UnsafeAuthSchemaServer) mustEmbedUnimplementedAuthSchemaServer() {
	_m.Called()
}

// NewUnsafeAuthSchemaServer creates a new instance of UnsafeAuthSchemaServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeAuthSchemaServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeAuthSchemaServer {
	mock := &UnsafeAuthSchemaServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
