// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePackageSchemaServer is an autogenerated mock type for the UnsafePackageSchemaServer type
type UnsafePackageSchemaServer struct {
	mock.Mock
}

// mustEmbedUnimplementedPackageSchemaServer provides a mock function with given fields:
func (_m *UnsafePackageSchemaServer) mustEmbedUnimplementedPackageSchemaServer() {
	_m.Called()
}

// NewUnsafePackageSchemaServer creates a new instance of UnsafePackageSchemaServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafePackageSchemaServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafePackageSchemaServer {
	mock := &UnsafePackageSchemaServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
