// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeUserSchemaServer is an autogenerated mock type for the UnsafeUserSchemaServer type
type UnsafeUserSchemaServer struct {
	mock.Mock
}

// mustEmbedUnimplementedUserSchemaServer provides a mock function with given fields:
func (_m *UnsafeUserSchemaServer) mustEmbedUnimplementedUserSchemaServer() {
	_m.Called()
}

// NewUnsafeUserSchemaServer creates a new instance of UnsafeUserSchemaServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeUserSchemaServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeUserSchemaServer {
	mock := &UnsafeUserSchemaServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
