// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: schema/v1/constant.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_UNKNOWN_GENDER Gender = 0
	Gender_MALE           Gender = 1
	Gender_FEMALE         Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "UNKNOWN_GENDER",
		1: "MALE",
		2: "FEMALE",
	}
	Gender_value = map[string]int32{
		"UNKNOWN_GENDER": 0,
		"MALE":           1,
		"FEMALE":         2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_v1_constant_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_schema_v1_constant_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_schema_v1_constant_proto_rawDescGZIP(), []int{0}
}

type PreferenceType int32

const (
	PreferenceType_UNKNOWN_PREFERENCE_TYPE PreferenceType = 0
	PreferenceType_PASS                    PreferenceType = 1
	PreferenceType_LIKE                    PreferenceType = 2
)

// Enum value maps for PreferenceType.
var (
	PreferenceType_name = map[int32]string{
		0: "UNKNOWN_PREFERENCE_TYPE",
		1: "PASS",
		2: "LIKE",
	}
	PreferenceType_value = map[string]int32{
		"UNKNOWN_PREFERENCE_TYPE": 0,
		"PASS":                    1,
		"LIKE":                    2,
	}
)

func (x PreferenceType) Enum() *PreferenceType {
	p := new(PreferenceType)
	*p = x
	return p
}

func (x PreferenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreferenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_v1_constant_proto_enumTypes[1].Descriptor()
}

func (PreferenceType) Type() protoreflect.EnumType {
	return &file_schema_v1_constant_proto_enumTypes[1]
}

func (x PreferenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreferenceType.Descriptor instead.
func (PreferenceType) EnumDescriptor() ([]byte, []int) {
	return file_schema_v1_constant_proto_rawDescGZIP(), []int{1}
}

var File_schema_v1_constant_proto protoreflect.FileDescriptor

var file_schema_v1_constant_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x2a, 0x32,
	0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x5f, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45,
	0x10, 0x02, 0x2a, 0x41, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x50, 0x52, 0x45, 0x46, 0x45, 0x52, 0x45, 0x4e, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x53, 0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x49, 0x4b, 0x45, 0x10, 0x02, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6e, 0x73, 0x32, 0x30, 0x31, 0x32, 0x2f, 0x64, 0x65, 0x61, 0x6c,
	0x6c, 0x73, 0x2d, 0x64, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_v1_constant_proto_rawDescOnce sync.Once
	file_schema_v1_constant_proto_rawDescData = file_schema_v1_constant_proto_rawDesc
)

func file_schema_v1_constant_proto_rawDescGZIP() []byte {
	file_schema_v1_constant_proto_rawDescOnce.Do(func() {
		file_schema_v1_constant_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_v1_constant_proto_rawDescData)
	})
	return file_schema_v1_constant_proto_rawDescData
}

var file_schema_v1_constant_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_schema_v1_constant_proto_goTypes = []interface{}{
	(Gender)(0),         // 0: v1.Gender
	(PreferenceType)(0), // 1: v1.PreferenceType
}
var file_schema_v1_constant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_v1_constant_proto_init() }
func file_schema_v1_constant_proto_init() {
	if File_schema_v1_constant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_v1_constant_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_v1_constant_proto_goTypes,
		DependencyIndexes: file_schema_v1_constant_proto_depIdxs,
		EnumInfos:         file_schema_v1_constant_proto_enumTypes,
	}.Build()
	File_schema_v1_constant_proto = out.File
	file_schema_v1_constant_proto_rawDesc = nil
	file_schema_v1_constant_proto_goTypes = nil
	file_schema_v1_constant_proto_depIdxs = nil
}
